-- H2 (PostgreSQL mode) compatible schema

CREATE TABLE IF NOT EXISTS notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  title VARCHAR(200) NOT NULL,
  content_md CLOB NOT NULL,
  content_text CLOB NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_id BIGINT NOT NULL,
  model VARCHAR(100) NOT NULL,
  style VARCHAR(20) NOT NULL,
  one_line VARCHAR(300) NOT NULL,
  paragraph CLOB NOT NULL,
  tokens_prompt INT NOT NULL,
  tokens_output INT NOT NULL,
  cost DECIMAL(10,6) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_summaries_note FOREIGN KEY (note_id) REFERENCES notes(id)
);

CREATE INDEX IF NOT EXISTS idx_notes_user_title ON notes(user_id, title);
CREATE INDEX IF NOT EXISTS idx_summaries_note_created ON summaries(note_id, created_at);
-- End of V1__init.sql